# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgehub/v3/edgehub.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'edgehub/v3/edgehub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65\x64gehub/v3/edgehub.proto\x12\x0b\x65\x64gehub.sdk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"J\n\x14GetDiscoveryResponse\x12\x32\n\x0e\x64iscovery_info\x18\x01 \x03(\x0b\x32\x1a.edgehub.sdk.DiscoveryInfo\"j\n\rDiscoveryInfo\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x37\n\x16\x61\x64\x64itional_information\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"\'\n\x11GetReadingRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\"Q\n\x12GetReadingResponse\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\'\n\x06\x66ields\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"N\n\x0fSendDataRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\'\n\x06\x66ields\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"U\n\x10SendDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12&\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.edgehub.sdk.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t2\xaf\x03\n\x0e\x45\x64geHubService\x12K\n\x0cGetDiscovery\x12\x16.google.protobuf.Empty\x1a!.edgehub.sdk.GetDiscoveryResponse\"\x00\x12O\n\nGetReading\x12\x1e.edgehub.sdk.GetReadingRequest\x1a\x1f.edgehub.sdk.GetReadingResponse\"\x00\x12_\n\x18GetReadingStreamResponse\x12\x1e.edgehub.sdk.GetReadingRequest\x1a\x1f.edgehub.sdk.GetReadingResponse\"\x00\x30\x01\x12I\n\x08SendData\x12\x1c.edgehub.sdk.SendDataRequest\x1a\x1d.edgehub.sdk.SendDataResponse\"\x00\x12S\n\x0eSendDataStream\x12\x1c.edgehub.sdk.SendDataRequest\x1a\x1d.edgehub.sdk.SendDataResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgehub.v3.edgehub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDISCOVERYRESPONSE']._serialized_start=100
  _globals['_GETDISCOVERYRESPONSE']._serialized_end=174
  _globals['_DISCOVERYINFO']._serialized_start=176
  _globals['_DISCOVERYINFO']._serialized_end=282
  _globals['_GETREADINGREQUEST']._serialized_start=284
  _globals['_GETREADINGREQUEST']._serialized_end=323
  _globals['_GETREADINGRESPONSE']._serialized_start=325
  _globals['_GETREADINGRESPONSE']._serialized_end=406
  _globals['_SENDDATAREQUEST']._serialized_start=408
  _globals['_SENDDATAREQUEST']._serialized_end=486
  _globals['_SENDDATARESPONSE']._serialized_start=488
  _globals['_SENDDATARESPONSE']._serialized_end=573
  _globals['_ERROR']._serialized_start=575
  _globals['_ERROR']._serialized_end=599
  _globals['_EDGEHUBSERVICE']._serialized_start=602
  _globals['_EDGEHUBSERVICE']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
