# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgehub.v3 import edgehub_pb2 as edgehub_dot_v3_dot_edgehub__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edgehub/v3/edgehub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdgeHubServiceStub(object):
    """Hub version: 2.2 release
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDiscovery = channel.unary_unary(
                '/edgehub.sdk.EdgeHubService/GetDiscovery',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=edgehub_dot_v3_dot_edgehub__pb2.GetDiscoveryResponse.FromString,
                _registered_method=True)
        self.GetReading = channel.unary_unary(
                '/edgehub.sdk.EdgeHubService/GetReading',
                request_serializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingRequest.SerializeToString,
                response_deserializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingResponse.FromString,
                _registered_method=True)
        self.GetReadingStreamResponse = channel.unary_stream(
                '/edgehub.sdk.EdgeHubService/GetReadingStreamResponse',
                request_serializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingRequest.SerializeToString,
                response_deserializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingResponse.FromString,
                _registered_method=True)
        self.SendData = channel.unary_unary(
                '/edgehub.sdk.EdgeHubService/SendData',
                request_serializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataRequest.SerializeToString,
                response_deserializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataResponse.FromString,
                _registered_method=True)
        self.SendDataStream = channel.stream_stream(
                '/edgehub.sdk.EdgeHubService/SendDataStream',
                request_serializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataRequest.SerializeToString,
                response_deserializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataResponse.FromString,
                _registered_method=True)


class EdgeHubServiceServicer(object):
    """Hub version: 2.2 release
    """

    def GetDiscovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadingStreamResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDataStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeHubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDiscovery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiscovery,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=edgehub_dot_v3_dot_edgehub__pb2.GetDiscoveryResponse.SerializeToString,
            ),
            'GetReading': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReading,
                    request_deserializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingRequest.FromString,
                    response_serializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingResponse.SerializeToString,
            ),
            'GetReadingStreamResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.GetReadingStreamResponse,
                    request_deserializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingRequest.FromString,
                    response_serializer=edgehub_dot_v3_dot_edgehub__pb2.GetReadingResponse.SerializeToString,
            ),
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataRequest.FromString,
                    response_serializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataResponse.SerializeToString,
            ),
            'SendDataStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SendDataStream,
                    request_deserializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataRequest.FromString,
                    response_serializer=edgehub_dot_v3_dot_edgehub__pb2.SendDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgehub.sdk.EdgeHubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgehub.sdk.EdgeHubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeHubService(object):
    """Hub version: 2.2 release
    """

    @staticmethod
    def GetDiscovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgehub.sdk.EdgeHubService/GetDiscovery',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            edgehub_dot_v3_dot_edgehub__pb2.GetDiscoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgehub.sdk.EdgeHubService/GetReading',
            edgehub_dot_v3_dot_edgehub__pb2.GetReadingRequest.SerializeToString,
            edgehub_dot_v3_dot_edgehub__pb2.GetReadingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReadingStreamResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/edgehub.sdk.EdgeHubService/GetReadingStreamResponse',
            edgehub_dot_v3_dot_edgehub__pb2.GetReadingRequest.SerializeToString,
            edgehub_dot_v3_dot_edgehub__pb2.GetReadingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgehub.sdk.EdgeHubService/SendData',
            edgehub_dot_v3_dot_edgehub__pb2.SendDataRequest.SerializeToString,
            edgehub_dot_v3_dot_edgehub__pb2.SendDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDataStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/edgehub.sdk.EdgeHubService/SendDataStream',
            edgehub_dot_v3_dot_edgehub__pb2.SendDataRequest.SerializeToString,
            edgehub_dot_v3_dot_edgehub__pb2.SendDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
